# Generated by Django 5.0 on 2024-10-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_detalleventa_subtotal_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagoxventas',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
