# Generated by Django 5.0 on 2024-10-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_detalleventa_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
